### PR TITLE
Fix people picker event handlers

### LINKED ISSUE #68: PeoplePicker: Remove button doesn't work
_From @manndave on March 7, 2016 17:51_

Button needs to be moved up into parent `li` for JS to work.  PR coming...

Repo steps: click "x" icon in a peoplepicker dropdown to remove result - nothing happens.

_Copied from original issue: OfficeDev/office-ui-fabric-core#414_

### PR DESCRIPTION
**Pull request by leddie24**
Fixes #68 and #139

- Add removeItem click handler inside of _clickHandler
- Update Members count on removal/add
- Fix css (persona was oval shaped in small breakpoint)

### CODE REVIEW

File: src/components/PeoplePicker/PeoplePicker.ts [hunk 1]
```diff
@@ -22,7 +22,9 @@ namespace fabric {
     private _peoplePickerSearchBox: Element;
     private _peoplePickerResults: NodeListOf<Element>;
     private _isContextualMenuOpen: Boolean;
-    private _selectedPeople: NodeListOf<Element>;
+    private _selectedPeople: Element;
+    private _selectedCount: Element;
+    private _selectedPlural: HTMLElement;
```
Comment (Jahnp) [inline src/components/PeoplePicker/PeoplePicker.ts]: Is there a good reason why this needs to be an `HTMLElement` vs plain `Element`?

**Comment by Jahnp** [comment]
Approved

**Comment by ericthompson** [comment]
Approved
