### PR TITLE
Fix multiple dropdown, fix double dismiss bug with panel dropdown

### LINKED ISSUE #184: Issue: Multiple Dropdowns stay opened simultaneously
Hi there,
I am using OfficeUIFabric Core 5.0.0 with with OfficeUIFabricJS 1.2.0 for building an Office365 add-in.

As you might have figured from the Title of the issue;
if you click open a drop down, and click on second drop down right after, the second one will open up up while the first stays open too.

Kindly look into it.
Thank you

### PR DESCRIPTION
**Pull request by leddie24**
Fixes #184 

- Dismisses other open dropdowns
- Fixes double dismiss bug with panel dropdown (if you click on the overlay with a panel dropdown, panelhost tries dismissing twice)

### CODE REVIEW

File: src/components/Dropdown/Dropdown.ts [hunk 1]
```diff
@@ -178,8 +185,15 @@ namespace fabric {
       }
     }
 
-    private _onCloseDropdown() {
-      this._removeDropdownAsPanel();
+    private closeOtherDropdowns() {
```
Comment (mikewheaton) [inline src/components/Dropdown/Dropdown.ts]: Prefix with an underscore to indicate this is a private method.

**Comment by mikewheaton** [comment]
Approved, thanks!

**Comment by Jahnp** [comment]
Approved. Awesome!!
